### ISSUE TITLE
match logic "premature" error.

### ISSUE THREAD

**Issue by huntzhan** [huntzhan/clidoc#62]
consider following `doc`:

```
Usage:
  utility_name flag-1 ARG1
  utility_name <arg3>...
```

If user input `./utility_name flag-1 a b c`, then the match logic would return with a match error. Reason: All nodes of synopsis line 1 are matched, then the top level `LogicXor` node detects a match branch, and then stop searching:

```
void MatchStrategy::ProcessNode(LogicXor::SharedPtr node) {
  for (auto child_node : node->children_) {
    child_node->Accept(this);
    if (child_match_condition_) {
      child_match_condition_ = true;
      return;
    }
  }
  child_match_condition_ = false;
}
```

**Comment by haoxun** [comment]
Fix plan: let top-level `LogicXor` node check argument match state.
